### ISSUE TITLE
关于.github /update-alias.py更新脚本如何使用的问题

### ISSUE THREAD

**Issue by KishibeRohan1979** [monsterxcn/nonebot-plugin-gsmaterial#12]
mo大佬您好，如题所示，我想尝试自己使用这个脚本更新数据的时候，报错如下

```python
python update-alias.py
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\software\work\pybot\nbBot\update-alias.py", line 31, in <module>
    AVATAR = read("AvatarExcelConfigData.json")
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\Desktop\software\work\pybot\nbBot\update-alias.py", line 6, in read
    return json.loads(Path(f"./{fn}").read_text(encoding="UTF-8"))
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\Desktop\software\work\python\python3.11\Lib\pathlib.py", line 1058, in read_text
    with self.open(mode='r', encoding=encoding, errors=errors) as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\Desktop\software\work\python\python3.11\Lib\pathlib.py", line 1044, in open
    return io.open(self, mode, buffering, encoding, errors, newline)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'AvatarExcelConfigData.json'
```

虽然我知道是因为我没有`AvatarExcelConfigData.json`的缘故，但是我并不知道这个`AvatarExcelConfigData.json`数据源在哪里，以及后续代码中提到的各种json文件。

所以想请教一下，这个脚本存放路径，以及这些数据源怎么查找？

**Comment by monsterxcn** [comment]
https://github.com/monsterxcn/nonebot-plugin-gsmaterial/blob/main/.github/workflows/update-alias.yml#L23-L31

结合这个看

GAMEDATA 那个是原神解包的仓库，找一下。

**Comment by monsterxcn** [comment]
CDN 证书过期了，过几天休假来修

可以暂时把 `data_source.py` 文件里的 `cdn.monsterx.cn` 全部替换成 `monsterx.oss-cn-shanghai.aliyuncs.com`，应该就能正常用了
